version: "3.7"
services:
        mysql:
                container_name: 'tech-blogs'
                image: 'mysql:8.0'
                environment:
                        - MYSQL_ROOT_PASSWORD=techblogs
                        - MYSQL_DATABASE=techblogs
                        - MYSQL_USER=techblogs
                        - MYSQL_PASSWORD=123456
                ports:
                        - "4406:3306"

                networks:
                - esnet
                volumes:
                - ./data/db/mysql:/var/lib/mysql
                command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

networks:
        esnet: